import html2pdf from 'html2pdf.js';

export const generateExpensePdf = (expenseData) => {
  // Extract expense details
  const expenseId = expenseData?._id ? expenseData._id.slice(-8) : 'N/A';
  const expenseDate = expenseData?.date ? new Date(expenseData.date).toLocaleDateString() : 'N/A';
  const category = expenseData?.category || 'N/A';
  const description = expenseData?.description || 'N/A';
  const paymentMode = expenseData?.paymentMode || 'N/A';
  const vendor = expenseData?.vendor || 'N/A';
  const amount = expenseData?.amount || 0;
  const shopName = expenseData?.shop?.name || (expenseData?.admin ? 'Admin' : 'N/A');
  
  // Generate the complete HTML for the PDF
  const expenseHtml = `
    <div style="font-family: Arial, sans-serif; padding: 30px; max-width: 800px; margin: 0 auto;">
      <!-- Header -->
      <div style="text-align: center; margin-bottom: 30px; border-bottom: 3px solid #333; padding-bottom: 20px;">
        <h1 style="color: #333; margin: 0; font-size: 32px;">The Sweet Hub</h1>
        <p style="color: #666; font-size: 16px; margin: 10px 0 5px 0;">156, Dubai Main Road, Thanjavur, Tamil Nadu - 613006</p>
        <p style="color: #666; font-size: 16px; margin: 5px 0;">Phone: 7339200636</p>
      </div>
      
      <div style="text-align: center; margin-bottom: 30px;">
        <h2 style="color: #333; margin: 0; font-size: 28px;">EXPENSE RECEIPT</h2>
      </div>
      
      <!-- Expense Details -->
      <div style="margin-bottom: 30px; background-color: #f8f9fa; padding: 20px; border-radius: 8px; border: 1px solid #dee2e6;">
        <h3 style="color: #333; margin-top: 0; font-size: 20px; padding-bottom: 10px; border-bottom: 2px solid #eee;">Expense Details</h3>
        <div style="display: flex; justify-content: space-between;">
          <div style="width: 48%;">
            <p style="margin: 8px 0; font-size: 16px;"><strong>Receipt ID:</strong> ${expenseId}</p>
            <p style="margin: 8px 0; font-size: 16px;"><strong>Date:</strong> ${expenseDate}</p>
            <p style="margin: 8px 0; font-size: 16px;"><strong>Shop:</strong> ${shopName}</p>
          </div>
          <div style="width: 48%; text-align: right;">
            <p style="margin: 8px 0; font-size: 16px;"><strong>Category:</strong> ${category}</p>
            <p style="margin: 8px 0; font-size: 16px;"><strong>Payment Mode:</strong> ${paymentMode}</p>
            <p style="margin: 8px 0; font-size: 16px;"><strong>Vendor:</strong> ${vendor}</p>
          </div>
        </div>
      </div>
      
      <!-- Description -->
      <div style="margin-bottom: 30px;">
        <h3 style="color: #333; margin-bottom: 15px; font-size: 20px; padding-bottom: 10px; border-bottom: 2px solid #eee;">Description</h3>
        <div style="border: 1px solid #ddd; padding: 20px; border-radius: 8px; min-height: 60px; background-color: #fff;">
          <p style="font-size: 16px; margin: 0; color: #333;">${description}</p>
        </div>
      </div>
      
      <!-- Amount -->
      <div style="text-align: right; margin-bottom: 40px;">
        <h3 style="color: #333; margin-bottom: 15px; font-size: 20px;">Amount</h3>
        <div style="border: 1px solid #ddd; padding: 25px; border-radius: 8px; background-color: #f9f9f9;">
          <p style="font-size: 32px; font-weight: bold; color: #333; margin: 0;">₹${amount.toFixed(2)}</p>
        </div>
      </div>
      
      <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; text-align: center;">
        <p style="color: #777; font-size: 14px; margin: 0;">
          Generated on ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}
        </p>
        <p style="color: #777; font-size: 14px; margin: 5px 0 0 0;">
          Receipt generated by The Sweet Hub Expense Management System
        </p>
      </div>
    </div>
  `;

  const opt = {
    margin: 15,
    filename: `expense_${expenseId}_${expenseDate.replace(/\//g, '-')}.pdf`,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: { scale: 2, useCORS: true },
    jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
  };

  // Generate and download the PDF
  html2pdf().from(expenseHtml).set(opt).save();
};