import html2pdf from 'html2pdf.js';

export const generateDepartmentReportPdf = (departments, filters = {}) => {
  // Format the date
  const currentDate = new Date().toLocaleDateString();
  
  // Calculate summary statistics
  const totalDepartments = departments.length;
  const totalWorkers = departments.reduce((sum, dept) => sum + (dept.workers ? dept.workers.length : 0), 0);
  
  // Generate department summary rows
  const departmentRows = departments.map(dept => {
    const workerCount = dept.workers ? dept.workers.length : 0;
    const workerNames = dept.workers && dept.workers.length > 0 
      ? dept.workers.map(worker => worker.name).join(', ') 
      : 'No workers';
    
    return `
      <tr>
        <td style="padding: 8px; border: 1px solid #ddd; font-size: 14px; font-weight: bold;">${dept.name || 'N/A'}</td>
        <td style="padding: 8px; border: 1px solid #ddd; text-align: center; font-size: 14px;">${workerCount}</td>
        <td style="padding: 8px; border: 1px solid #ddd; font-size: 14px;">${workerNames}</td>
      </tr>
    `;
  }).join('');

  // Generate filter information
  const filterInfo = [];
  if (filters.shop) filterInfo.push(`Shop: ${filters.shop}`);

  const filterText = filterInfo.length > 0 ? 
    `<p style="margin: 8px 0; font-size: 16px;"><strong>Filters Applied:</strong> ${filterInfo.join(', ')}</p>` : 
    '';

  // Generate the complete HTML for the PDF
  const reportHtml = `
    <div style="font-family: Arial, sans-serif; padding: 20px; max-width: 1000px; margin: 0 auto;">
      <!-- Header -->
      <div style="text-align: center; margin-bottom: 30px; border-bottom: 3px solid #333; padding-bottom: 20px;">
        <h1 style="color: #333; margin: 0; font-size: 32px;">The Sweet Hub</h1>
        <p style="color: #666; font-size: 16px; margin: 10px 0 5px 0;">156, Dubai Main Road, Thanjavur, Tamil Nadu - 613006</p>
        <p style="color: #666; font-size: 16px; margin: 5px 0;">Phone: 7339200636</p>
      </div>
      
      <div style="text-align: center; margin-bottom: 30px;">
        <h2 style="color: #333; margin: 0; font-size: 28px;">DEPARTMENT REPORT</h2>
        <p style="color: #666; font-size: 18px; margin: 15px 0;">
          Generated on ${currentDate}
        </p>
        ${filterText}
      </div>
      
      <!-- Summary -->
      <div style="margin-bottom: 30px; background-color: #f8f9fa; padding: 20px; border-radius: 8px; border: 1px solid #dee2e6;">
        <h3 style="color: #333; margin-top: 0; font-size: 20px;">Report Summary</h3>
        <div style="display: flex; justify-content: space-around; text-align: center;">
          <div>
            <p style="font-size: 16px; color: #666; margin: 0;">Total Departments</p>
            <p style="font-size: 28px; font-weight: bold; color: #333; margin: 10px 0 0 0;">${totalDepartments}</p>
          </div>
          <div>
            <p style="font-size: 16px; color: #666; margin: 0;">Total Workers</p>
            <p style="font-size: 28px; font-weight: bold; color: #333; margin: 10px 0 0 0;">${totalWorkers}</p>
          </div>
        </div>
      </div>
      
      <!-- Detailed Departments -->
      <div style="margin-bottom: 30px;">
        <h3 style="color: #333; margin-bottom: 15px; font-size: 20px; padding-bottom: 10px; border-bottom: 2px solid #eee;">Department Details</h3>
        <table style="width: 100%; border-collapse: collapse; margin-bottom: 20px;">
          <thead>
            <tr style="background-color: #e9ecef;">
              <th style="padding: 12px; border: 1px solid #ddd; text-align: left; font-size: 16px; font-weight: bold;">Department Name</th>
              <th style="padding: 12px; border: 1px solid #ddd; text-align: center; font-size: 16px; font-weight: bold;">Worker Count</th>
              <th style="padding: 12px; border: 1px solid #ddd; text-align: left; font-size: 16px; font-weight: bold;">Workers</th>
            </tr>
          </thead>
          <tbody>
            ${departmentRows}
          </tbody>
        </table>
      </div>
      
      <div style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; text-align: center;">
        <p style="color: #777; font-size: 14px; margin: 0;">
          Generated on ${currentDate} at ${new Date().toLocaleTimeString()}
        </p>
        <p style="color: #777; font-size: 14px; margin: 5px 0 0 0;">
          Report generated by The Sweet Hub Department Management System
        </p>
      </div>
    </div>
  `;

  const opt = {
    margin: 15,
    filename: `department_report_${currentDate.replace(/\//g, '-')}.pdf`,
    image: { type: 'jpeg', quality: 0.98 },
    html2canvas: { scale: 2, useCORS: true },
    jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
  };

  // Generate and download the PDF
  html2pdf().from(reportHtml).set(opt).save();
};