import React, { useState, useEffect, useContext } from 'react';
import { LuPlus, LuSearch, LuFileText, LuTruck, LuDownload } from 'react-icons/lu';
import { useNavigate } from 'react-router-dom';
import { useEWayBills } from '../../../context/EWayBillContext';
import { generateEWayBillPdf } from '../../../utils/generateEWayBillPdf';

const EWayBillsHistory = () => {
	const navigate = useNavigate();
	const { ewayBills } = useEWayBills();
	
	const [filteredBills, setFilteredBills] = useState(ewayBills);
	const [searchTerm, setSearchTerm] = useState('');
	const [filterStatus, setFilterStatus] = useState('');

	useEffect(() => {
		let result = ewayBills;
		
		// Apply search filter
		if (searchTerm) {
			const term = searchTerm.toLowerCase();
			result = result.filter(bill => 
				bill.ewbNumber.toLowerCase().includes(term) ||
				bill.documentNumber.toLowerCase().includes(term) ||
				bill.generatedBy.toLowerCase().includes(term)
			);
		}
		
		// Apply status filter
		if (filterStatus && filterStatus !== 'All') {
			result = result.filter(bill => bill.status === filterStatus);
		}
		
		setFilteredBills(result);
	}, [searchTerm, filterStatus, ewayBills]);

	const getStatusClass = (status) => {
		switch (status) {
			case 'Active':
				return 'bg-green-100 text-green-800';
			case 'Expired':
				return 'bg-red-100 text-red-800';
			default:
				return 'bg-gray-100 text-gray-800';
		}
	};

	const formatDate = (dateString) => {
		const options = { year: 'numeric', month: 'short', day: 'numeric' };
		return new Date(dateString).toLocaleDateString(undefined, options);
	};

	const handleDownloadPdf = (bill) => {
		generateEWayBillPdf(bill);
	};

	return (
		<div className="space-y-6">
			{/* Header */}
			<div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
				<div>
					<h1 className="text-3xl font-bold text-gray-800">E-Way Bills History</h1>
					<p className="text-gray-600">View and manage all E-Way bills</p>
				</div>
				<button
					onClick={() => navigate('/admin/eway-bills/create')}
					className="flex items-center gap-2 px-4 py-2 bg-gradient-to-r from-blue-500 to-indigo-600 hover:from-blue-600 hover:to-indigo-700 text-white rounded-lg shadow-md hover:shadow-lg transition-all"
				>
					<LuPlus className="text-lg" />
					<span>Create E-Way Bill</span>
				</button>
			</div>

			{/* Filters */}
			<div className="bg-white rounded-xl shadow-sm border border-gray-100 p-6">
				<div className="grid grid-cols-1 md:grid-cols-3 gap-4">
					<div className="md:col-span-2">
						<div className="relative">
							<div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
								<LuSearch className="text-gray-400" />
							</div>
							<input
								type="text"
								placeholder="Search by E-Way Bill Number, Document Number..."
								className="w-full pl-10 pr-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
								value={searchTerm}
								onChange={(e) => setSearchTerm(e.target.value)}
							/>
						</div>
					</div>
					
					<div>
						<select
							className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
							value={filterStatus}
							onChange={(e) => setFilterStatus(e.target.value)}
						>
							<option value="">Select Status</option>
							<option value="Active">Active</option>
							<option value="Expired">Expired</option>
						</select>
					</div>
				</div>
			</div>

			{/* E-Way Bills Table */}
			<div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
				<div className="overflow-x-auto">
					<table className="min-w-full divide-y divide-gray-200">
						<thead className="bg-gray-50">
							<tr>
								<th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
									E-Way Bill Number
								</th>
								<th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
									Document Number
								</th>
								<th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
									Generated By
								</th>
								<th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
									Generated Date
								</th>
								<th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
									Valid Period
								</th>
								<th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
									Total Amount
								</th>
								<th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
									Status
								</th>
								<th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
									Actions
								</th>
							</tr>
						</thead>
						<tbody className="bg-white divide-y divide-gray-200">
							{filteredBills.length > 0 ? (
								filteredBills.map((bill) => (
									<tr key={bill.id} className="hover:bg-gray-50">
										<td className="px-6 py-4 whitespace-nowrap">
											<div className="flex items-center">
												<LuTruck className="text-gray-400 mr-2" />
												<div className="text-sm font-medium text-gray-900">{bill.ewbNumber}</div>
											</div>
										</td>
										<td className="px-6 py-4 whitespace-nowrap">
											<div className="text-sm text-gray-900">{bill.documentNumber}</div>
										</td>
										<td className="px-6 py-4 whitespace-nowrap">
											<div className="text-sm text-gray-900">{bill.generatedBy}</div>
										</td>
										<td className="px-6 py-4 whitespace-nowrap">
											<div className="text-sm text-gray-900">{formatDate(bill.generatedDate)}</div>
										</td>
										<td className="px-6 py-4 whitespace-nowrap">
											<div className="text-sm text-gray-900">
												{formatDate(bill.validFrom)} to {formatDate(bill.validTo)}
											</div>
										</td>
										<td className="px-6 py-4 whitespace-nowrap">
											<div className="text-sm text-gray-900">₹{(bill.totalAmount || 0).toFixed(2)}</div>
										</td>
										<td className="px-6 py-4 whitespace-nowrap">
											<span className={`px-2 inline-flex text-xs leading-5 font-semibold rounded-full ${getStatusClass(bill.status)}`}>
												{bill.status}
											</span>
										</td>
										<td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
											<div className="flex items-center space-x-2">
												<button
													onClick={() => navigate(`/admin/eway-bills/view/${bill.id}`)}
													className="text-blue-600 hover:text-blue-900 flex items-center gap-1"
												>
													<LuFileText className="text-sm" />
													<span>View</span>
												</button>
												<button
													onClick={() => handleDownloadPdf(bill)}
													className="text-green-600 hover:text-green-900 flex items-center gap-1"
												>
													<LuDownload className="text-sm" />
													<span>PDF</span>
												</button>
											</div>
										</td>
									</tr>
								))
							) : (
								<tr>
									<td colSpan="8" className="px-6 py-4 text-center text-sm text-gray-500">
										No E-Way bills found
									</td>
								</tr>
							)}
						</tbody>
					</table>
				</div>
			</div>

			{/* Summary Cards */}
			<div className="grid grid-cols-1 md:grid-cols-3 gap-6">
				<div className="bg-white rounded-xl shadow-sm border border-gray-100 p-6">
					<div className="flex items-center">
						<div className="p-3 rounded-lg bg-blue-100">
							<LuTruck className="text-blue-600 text-xl" />
						</div>
						<div className="ml-4">
							<h3 className="text-lg font-semibold text-gray-800">Total E-Way Bills</h3>
							<p className="text-2xl font-bold text-gray-900">{ewayBills.length}</p>
						</div>
					</div>
				</div>
				
				<div className="bg-white rounded-xl shadow-sm border border-gray-100 p-6">
					<div className="flex items-center">
						<div className="p-3 rounded-lg bg-green-100">
							<LuTruck className="text-green-600 text-xl" />
						</div>
						<div className="ml-4">
							<h3 className="text-lg font-semibold text-gray-800">Active E-Way Bills</h3>
							<p className="text-2xl font-bold text-gray-900">
								{ewayBills.filter(bill => bill.status === 'Active').length}
							</p>
						</div>
					</div>
				</div>
				
				<div className="bg-white rounded-xl shadow-sm border border-gray-100 p-6">
					<div className="flex items-center">
						<div className="p-3 rounded-lg bg-red-100">
							<LuTruck className="text-red-600 text-xl" />
						</div>
						<div className="ml-4">
							<h3 className="text-lg font-semibold text-gray-800">Expired E-Way Bills</h3>
							<p className="text-2xl font-bold text-gray-900">
								{ewayBills.filter(bill => bill.status === 'Expired').length}
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	);
};

export default EWayBillsHistory;